# Generated by Django 5.0.6 on 2025-09-07 16:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManuscriptAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('input_type', models.CharField(choices=[('text', 'Text'), ('pdf', 'PDF')], default='text', max_length=10)),
                ('manuscript_text', models.TextField(validators=[django.core.validators.MinLengthValidator(50)])),
                ('summary', models.TextField()),
                ('keywords', models.JSONField(default=list)),
                ('language_quality', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processing_time', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Manuscript Analysis',
                'verbose_name_plural': 'Manuscript Analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(max_length=100)),
                ('error_message', models.TextField()),
                ('input_type', models.CharField(choices=[('text', 'Text'), ('pdf', 'PDF')], default='text', max_length=10)),
                ('input_size', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
